<?php

//Import Wechat
require_once 'weichat.class.php';
const WECHAT_APPID = 'wxa4ddad61df39d191';
const WECHAT_APPSECRET = '298befb9e2bd11279f8af392390803dd';
const WECHAT_TOKEN = '';

header('Content-Type:text/html; charset=utf-8');

/**
 * Implements hook_menu
 */
function tri_wechat_register_menu() {
	$items = array();	
	$items['tri-wechat-register'] =  array(
		'title' => 'Register for Wechat',
		'page callback' => 'tri_wechat_register_page',
		'access arguments' => array('access content'), 
	);
	return $items;
}


/**
 * Page callback
 */
function tri_wechat_register_page() {
	if(empty($_POST)) {
		$openid = _get_wechat_openid();
		if( $openid) {
			$_SESSION['openid'] = $openid;
		} else {
			exit;
		}
	} else {
		$openid = $_SESSION['openid'];
	}
	
	$chk = _id_have_registered($openid);
	if($chk == 'not_registered') {
		//show register form
		return drupal_get_form('tri_wechat_register_form');
	}
	elseif( $chk == 'not_approved') {
		//TODO: show not_approved
		$content = t('You account has been registed and waiting to be approved.');
	} 
	else {	//'have_approved'
		//TODO: auto login
		$content = t('You account has been approved. Now we login automatically...');
	}
	
	return $content;
}

/**
 * help function
 */
function _get_wechat_openid() {
	#krumo($_GET);
	//1. 授权回调网页域名 更新。
	//2. 菜单入口 更新，比如:
	//https://open.weixin.qq.com/connect/oauth2/authorize?appid=wxa4ddad61df39d191&redirect_uri=http%3A%2F%2F6kaqbc.natappfree.cc%2Ftri-wechat-register&response_type=code&scope=snsapi_base&state=0#wechat_redirect
	
	$wc = new WeiChat(WECHAT_APPID, WECHAT_APPSECRET, WECHAT_TOKEN);
	$openid = $wc->getOAuth2UserInfo(true);
	#krumo($openid);
	
    return $openid;
    #return 'abcdefghijklmn1234567890';
}

/**
 * help funtion
 */
function _id_have_registered($openid) {
	//read wechat_login_user
	$query = db_select('wechat_login_user', 'w');
	$query->join('users', 'u', 'w.uid = u.uid');
	$result = $query->fields('w', array('openid'))
		->fields('u', array('uid', 'status'))
		->condition('openid', $openid)
		->execute()->fetch();
	#krumo($result);
	
	if($result === FALSE) {
		return 'not_registered';
	} elseif( $result->status == 0) {
		return 'not_approved';
	} else {
		return 'have_approved';
	}
}


/**
 * Form create
 */
function tri_wechat_register_form($form, &$form_state) {
    $form['username'] = array(
            '#type' => 'textfield',
            '#title' => t('Username'),
            '#description' => t('Your username.'),
            '#required' => TRUE,
    );
    $form['password'] = array(
            '#type' => 'password_confirm',
            '#title' => t('Password'),
            '#description' => t('Your password.'),
            '#required' => TRUE,
    );
    $form['email'] = array(
            '#type' => 'textfield',
            '#title' => t('Email'),
            '#description' => t('Email address.'),
            '#required' => TRUE,
    );
    $form['mobile'] = array(
            '#type' => 'textfield',
            '#title' => t('Mobile'),
            '#description' => t('Mobile phoone number'),
            '#required' => TRUE,
    );
    //Submit
    $form['buttons']['submit'] = array(
            '#type' => 'submit',
            '#value' => t('Register'),
    );
	
    return $form;
}


/**
 * Form validate
 */
function tri_wechat_register_form_validate(&$form, &$form_state) {
    //Necessary validation
	//valid username
	if( $user_error = user_validate_name($form_state['values']['username'])) {
		form_set_error('username', $user_error);
	}
	
	//valid password?
	$re = '/^[a-z0-9_-]{6,18}$/i';
	if( preg_match($re, $form_state['values']['password']) == 0) {
		form_set_error('password', t('Please use a safer password.'));
	}
	
	//valid email
	if( valid_email_address($form_state['values']['email'])===false) {
		form_set_error('email', t('Please input a valid email address.'));
	}
	
	//valid mobile number
	$re = '/(^(13\d|15[^4,\D]|17[13678]|18\d)\d{8}|170[^346,\D]\d{7})$/i';
	if( preg_match($re, $form_state['values']['mobile']) == 0) {
		form_set_error('mobile', t('Please input a valid mobile number.'));
	}
}


/**
 * Form submit
 */
function tri_wechat_register_form_submit(&$form, &$form_state) {
    //create user
	$field_mobile =  array(
		'und' => array(
			0 => array(
				'value' => $form_state['values']['mobile'],
			),
		),
	);
	$fields = array(
		'name' => $form_state['values']['username'],
		'mail' => $form_state['values']['email'],
		'pass' => $form_state['values']['password'],
		'status' => 0,
		'field_mobile' => $field_mobile,
		'init' => $form_state['values']['email'],
		'roles' => array(
			4 => 'wechat authenticated',
		),
	);
	$account = user_save('', $fields);
	#krumo($account); exit;
    
    //save to wechat table(with openid)
	$openid = $_SESSION['openid'];
	_save_wechat_login_user($openid, $account->uid);
	
	//redirect
	$form_state['redirect'] = 'TODO';	//show not_approved OR no redirect?
}

/**
 * Help function
 */
function _save_wechat_login_user($openid, $uid) {
    $query = db_insert('wechat_login_user')
		->fields(array('openid','uid'))
		->values(array(
			'openid' => $openid,
			'uid' => $uid,
		))
		->execute();
}



