<?php

/**
 * Implements hook_menu
 */
function tri_wechat_register_menu() {
	$items = array();	
	$items['tri-wechat-register'] =  array(
		'title' => 'Wechat entrance',
		'page callback' => 'tri_wechat_register_page',
		'access arguments' => array('access content'), 
	);
	return $items;
}


/**
 * Page callback
 */
function tri_wechat_register_page() {
	$openid = _get_wechat_openid();
	
	$chk = _id_have_registered($openid);
	if($chk == 'not_registered') {
		//show register form
		return drupal_get_form('tri_wechat_register_form');
	}
	elseif( $chk == 'not_approved') {
		//TODO: do some PROMPT
	} 
	else {	//'have_approved'
		//TODO: auto login
	}
	
	return 'hello';
}

/**
 * help function
 */
function _get_wechat_openid() {
    return 'abcdefg123';
}

/**
 * help funtion
 */
function _id_have_registered($openid) {
    return 'not_registered';
}


/**
 * Form create
 */
function tri_wechat_register_form($form, &$form_state) {
    $form['username'] = array(
            '#type' => 'textfield',
            '#title' => t('Username'),
            '#description' => t('Your username.'),
            '#required' => TRUE,
    );
    $form['password'] = array(
            '#type' => 'password_confirm',
            '#title' => t('Password'),
            '#description' => t('Your password.'),
            '#required' => TRUE,
    );
    $form['email'] = array(
            '#type' => 'textfield',
            '#title' => t('Email'),
            '#description' => t('Email address.'),
            '#required' => TRUE,
    );
    $form['mobile'] = array(
            '#type' => 'textfield',
            '#title' => t('Mobile'),
            '#description' => t('Mobile phoone number'),
            '#required' => TRUE,
    );
    //Submit
    $form['buttons']['submit'] = array(
            '#type' => 'submit',
            '#value' => t('Register'),
    );

    return $form;
}


/**
 * Form validate
 */
function tri_wechat_register_form_validate(&$form, &$form_state) {
    //TODO: necessary validation
}


/**
 * Form submit
 */
function tri_wechat_register_form_submit(&$form, &$form_state) {
    //create user
    
    //save to wechat table(with openid)
}

/**
 * Help function
 */
function _save_wechat_login_user($openid, $uid) {
    
}



